### ISSUE TITLE
Colony Attacks

### ISSUE THREAD

**Issue by geomeza** [eoriont/space-empires#13]
You have no_attack in colonies set to false but during combat you just pass colony. You should just do if unit.no_attack pass else do the combat. That stops the just singling out colonies.

**Comment by eoriont** [comment]
Fixed. Although I forget exactly when I did it.

`combat_engine.py 14-20`
```py
            # units is in combat order, so loop through as attacker
            for attacker in units:
                # Units that can't attack shouldn't be considered
                if attacker.no_attack or not attacker.alive:
                    continue
```
