### ISSUE TITLE
Your new strat player

### ISSUE THREAD

**Issue by C0BBL3** [eoriont/space-empires#4]
For your decide_ship_movement function, you have to return the position, Justin told me so the game can check if the ship's new position is within its movement capability so Justin's strat player doesn't just teleport port behind you and say "nothing personal kid" and win.

**Comment by eoriont** [comment]
Check the comment at the very top of the decide move ship function (in `elijah_strategy_player`) It says I will return the movements. It may not say return, but this is actually a very overformatted version of pseudocode. (Pseudocode is literally english formatted like code)
